<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LTIN236815" failures="1" tests="10" name="testNG.MainTestng" time="29.258" errors="0" timestamp="2024-02-28T16:35:46 IST" skipped="5">
  <testcase classname="testNG.MainTestng" name="Searching_Bookshelves" time="1.960"/>
  <system-out/>
  <testcase classname="testNG.MainTestng" name="Apply_Slider" time="11.732"/>
  <system-out/>
  <testcase classname="testNG.MainTestng" name="Exclude_and_Sort" time="5.786"/>
  <system-out/>
  <testcase classname="testNG.MainTestng" name="Print_Submenu_items_and_productinfo" time="8.604"/>
  <system-out/>
  <testcase classname="testNG.MainTestng" name="Go_To_GiftCardsSection" time="1.176">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at testNG.MainTestng.Go_To_GiftCardsSection(MainTestng.java:111)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:219)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Go_To_GiftCardsSection -->
  <system-out/>
  <testcase classname="testNG.MainTestng" name="Enter_Amount" time="0.000">
    <skipped/>
  </testcase> <!-- Enter_Amount -->
  <system-out/>
  <testcase classname="testNG.MainTestng" name="Fill_Form_with_Invalid_info" time="0.000">
    <skipped/>
  </testcase> <!-- Fill_Form_with_Invalid_info -->
  <system-out/>
  <testcase classname="testNG.MainTestng" name="Capture_ErrorMessage" time="0.000">
    <skipped/>
  </testcase> <!-- Capture_ErrorMessage -->
  <system-out/>
  <testcase classname="testNG.MainTestng" name="Fill_Form_with_Valid_data" time="0.000">
    <skipped/>
  </testcase> <!-- Fill_Form_with_Valid_data -->
  <system-out/>
  <testcase classname="testNG.MainTestng" name="Validate_Entered_Details" time="0.000">
    <skipped/>
  </testcase> <!-- Validate_Entered_Details -->
  <system-out/>
</testsuite> <!-- testNG.MainTestng -->
